language: python
python:
  - "3.5"
sudo: required
branches:
  only:
  - master
before_install:
  - openssl aes-256-cbc -K $encrypted_6055c90bf0c8_key -iv $encrypted_6055c90bf0c8_iv -in publish-key.enc -out ~/.ssh/publish-key -d
  - chmod u=rw,og= ~/.ssh/publish-key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
  - echo "Configure locale"
  - sudo locale-gen pt_BR pt_BR.UTF-8
  - sudo dpkg-reconfigure locales
  - LC_TIME=pt_BR.UTF-8
  - date
  - locale -a
  - git remote set-url origin git@github.com:gustavofoa/gustavofurtado.com.br.git
  - git fetch origin -f gh-pages:gh-pages
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
script:
  - make github
